### ISSUE TITLE
Invalid configuration file.

### ISSUE THREAD

**Issue by HarrisonLond** [jpmikkers/TFTPServer#1]
A static configuration file is set in program.cs, 

Could you upload a template/example for the xml formatting to refer to. I have attempted manually recreating the path "C:\programdata\JPMikkers\TFTP Server\Configuration.xml" but experience exceptions. 

Many thanks.

**Comment by jpmikkers** [comment]
This is a configuration file using the defaults and a tftp home directory 'c:\tftphome'. Don't forget to create the home directory and change the endpoint  to your network cards' address.

[Configuration.xml.txt](https://github.com/jpmikkers/TFTPServer/files/5433918/Configuration.xml.txt)
