### ISSUE TITLE
How to set the Blocksize when create TFTP object?

### ISSUE THREAD

**Issue by n-ice-ch** [jpmikkers/TFTPServer#3]
The WindowSize is offered as parameter:
`public int TFTPWindowSize { get; set; } = 8;`
`tftp_server.WindowSize = (ushort)TFTPWindowSize;    // = Default: 1`

**But I see no possbility to set the DefaultBlockSize when create the TFTP object.**

May can you help me and add something similar to the code?
`public int TFTPBlockSize { get; set; } = 8192;`
`tftp_server.DefaultBlockSize = TFTPBlockSize ;    // = Default: 512`

**Comment by jpmikkers** [comment]
Hi, unfortunately increasing the block size is something that _must_ be requested by the tftp **client**. If the server would send larger packets without this negotiation, it could potentially lead to buffer overruns or corrupted file transfers to the client (and so possibly bricking devices during firmware upload).

**Comment by n-ice-ch** [comment]
I understand the problem. 
Thank you for the fast answer.
